// Dev-bypass fixtures for the Opportunities tab.
//
// Caribbean-flavoured mock data so the feed, filters, and tracker read
// as real during design review. Deadlines are computed relative to
// "now" so every deadline bucket (this week / this month / later / no
// deadline) always has content.

import type { Opportunity } from "./types";

const MONTHS = [
	"Jan",
	"Feb",
	"Mar",
	"Apr",
	"May",
	"Jun",
	"Jul",
	"Aug",
	"Sep",
	"Oct",
	"Nov",
	"Dec",
];

/** "12 Aug 2026"-style deadline `n` days from now. */
function inDays(n: number): string {
	const d = new Date(Date.now() + n * 86_400_000);
	return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`;
}

function daysAgo(n: number): string {
	return new Date(Date.now() - n * 86_400_000).toISOString();
}

export const MOCK_OPPORTUNITIES: Opportunity[] = [
	{
		id: "mock-ncb-grad",
		title: "Graduate Analyst Programme 2026",
		org: "NCB Financial Group",
		category_id: "job",
		opportunity_type: "Full-time, graduate intake",
		location: "Kingston, Jamaica",
		deadline: inDays(5),
		why: "Jamaica's largest bank hires a small analyst cohort once a year — rotations across digital, risk, and payments.",
		external_url: "https://www.jncb.com/careers",
		published_at: daysAgo(1),
	},
	{
		id: "mock-jnf-challenge",
		title: "Youth Social Entrepreneurship Challenge",
		org: "JN Foundation",
		category_id: "competition",
		opportunity_type: "Pitch competition",
		location: "Kingston, Jamaica",
		deadline: inDays(6),
		why: "Seed funding plus mentorship for ventures solving a real community problem — past winners came from all 14 parishes.",
		external_url: "https://www.jnfoundation.com",
		published_at: daysAgo(2),
	},
	{
		id: "mock-undp-volunteer",
		title: "Caribbean Youth Resilience Corps",
		org: "UNDP Caribbean",
		category_id: "volunteering",
		opportunity_type: "Volunteer placement",
		location: "Caribbean-wide",
		deadline: inDays(10),
		why: "Field placements in climate-resilience projects across CARICOM states — strong pathway into development careers.",
		external_url: "https://www.undp.org/latin-america",
		published_at: daysAgo(2),
	},
	{
		id: "mock-digicel-grant",
		title: "Community Impact Grant — Digital Inclusion",
		org: "Digicel Foundation",
		category_id: "grant",
		opportunity_type: "Grant, up to US$10,000",
		location: "Kingston, Jamaica",
		deadline: inDays(12),
		why: "Funds youth-led projects that close the digital divide in underserved communities.",
		external_url: "https://www.digicelfoundation.org",
		published_at: daysAgo(3),
	},
	{
		id: "mock-sagicor-intern",
		title: "Actuarial Summer Internship",
		org: "Sagicor Financial",
		category_id: "internship",
		opportunity_type: "Paid internship, 10 weeks",
		location: "Bridgetown, Barbados",
		deadline: inDays(15),
		why: "One of the region's few structured actuarial pipelines — exam support included.",
		external_url: "https://www.sagicor.com/careers",
		published_at: daysAgo(4),
	},
	{
		id: "mock-heart-course",
		title: "Digital Skills Bootcamp — Level 3 Certification",
		org: "HEART/NSTA Trust",
		category_id: "course",
		opportunity_type: "Free certification course",
		location: "Kingston & Montego Bay, Jamaica",
		deadline: inDays(20),
		why: "Free NVQ-J certification in software and data skills; evening cohorts for working applicants.",
		external_url: "https://www.heart-nsta.org",
		published_at: daysAgo(5),
	},
	{
		id: "mock-branson-accel",
		title: "Caribbean Entrepreneur Accelerator, Cohort 12",
		org: "Branson Centre of Entrepreneurship",
		category_id: "accelerator",
		opportunity_type: "12-week accelerator",
		location: "Caribbean-wide (hybrid, Montego Bay HQ)",
		deadline: inDays(25),
		why: "Investment-readiness programme for revenue-stage Caribbean founders; alumni have raised US$30M+.",
		external_url: "https://www.bransoncentre.co",
		published_at: daysAgo(6),
	},
	{
		id: "mock-gk-birthright",
		title: "Jamaican Birthright Internship Programme",
		org: "GraceKennedy Group",
		category_id: "internship",
		opportunity_type: "Paid summer internship",
		location: "Kingston, Jamaica",
		deadline: inDays(38),
		why: "Diaspora and local students rotate through GK's food and finance divisions with executive mentorship.",
		external_url: "https://www.gracekennedy.com",
		published_at: daysAgo(7),
	},
	{
		id: "mock-climate-fellowship",
		title: "Caribbean Climate Leaders Fellowship",
		org: "Open Society / CANARI",
		category_id: "fellowship",
		opportunity_type: "12-month fellowship, stipend",
		location: "Caribbean-wide",
		deadline: inDays(40),
		why: "Funded year working on climate adaptation policy with regional institutions.",
		external_url: "https://canari.org",
		published_at: daysAgo(8),
	},
	{
		id: "mock-uwi-scholarship",
		title: "Postgraduate Scholarship in Data Science",
		org: "UWI Mona",
		category_id: "scholarship",
		opportunity_type: "Full tuition + stipend",
		location: "Kingston, Jamaica",
		deadline: inDays(45),
		why: "Covers the MSc in Data Science; preference for applicants with community-impact project ideas.",
		external_url: "https://www.mona.uwi.edu",
		published_at: daysAgo(9),
	},
	{
		id: "mock-cmi-mentorship",
		title: "Rise Mentorship Programme 2026",
		org: "Caribbean Mentorship Institute",
		category_id: "mentorship",
		opportunity_type: "6-month mentorship",
		location: "Remote (Caribbean-wide)",
		deadline: inDays(50),
		why: "Pairs early-career professionals with senior Caribbean leaders in tech, finance, and the creative economy.",
		external_url: "https://www.caribbeanmentorship.org",
		published_at: daysAgo(10),
	},
	{
		id: "mock-techbeach",
		title: "Tech Beach Retreat 2026",
		org: "Tech Beach",
		category_id: "conference",
		opportunity_type: "Conference + scholarship passes",
		location: "Montego Bay, Jamaica",
		deadline: inDays(60),
		why: "The region's flagship tech conference; student scholarship passes open now.",
		external_url: "https://www.techbeachretreat.com",
		published_at: daysAgo(11),
	},
	{
		id: "mock-ansa-trainee",
		title: "Management Trainee Programme",
		org: "ANSA McAL Group",
		category_id: "job",
		opportunity_type: "Full-time, rotational",
		location: "Port of Spain, Trinidad & Tobago",
		deadline: "Rolling",
		why: "Two-year rotation across the group's manufacturing, media, and financial companies.",
		external_url: "https://www.ansamcal.com/careers",
		published_at: daysAgo(12),
	},
	{
		id: "mock-remote-frontend",
		title: "Frontend Engineer (Caribbean applicants welcome)",
		org: "Bboxx",
		category_id: "job",
		opportunity_type: "Full-time, remote",
		location: "Remote (Jamaica eligible)",
		deadline: "Rolling",
		why: "Clean-energy scale-up actively recruiting engineers from the region.",
		external_url: "https://www.bboxx.com/careers",
		published_at: daysAgo(13),
	},
	{
		id: "mock-carifesta-event",
		title: "CARIFESTA XVI Creative Showcase — Open Call",
		org: "CARICOM Secretariat",
		category_id: "event",
		opportunity_type: "Open call for creatives",
		location: "Bridgetown, Barbados",
		deadline: inDays(70),
		why: "Regional stage for Caribbean artists and designers; travel support for selected exhibitors.",
		external_url: "https://www.carifesta.net",
		published_at: daysAgo(14),
	},
];
