-- Retire the daily-mission cron.
--
-- The Task tab now renders the monthly goal (monthly_missions /
-- monthly_mission_steps, generated by the 'monthly-missions' cron) instead of
-- the per-day missions table. The daily-mission generator is no longer
-- surfaced anywhere, so stop scheduling it. This only unschedules the cron —
-- the trigger_daily_mission_job() function, the daily-mission edge function,
-- and the missions / user_mission_tasks tables are left in place (historical
-- data; the Signal score still reads any legacy user_mission_tasks rows).

do $$
begin
    if exists (select 1 from cron.job where jobname = 'daily-mission') then
        perform cron.unschedule('daily-mission');
    end if;
end $$;
