// Country name → flag emoji, for the community surfaces. Profiles store country
// as the display name from the COUNTRIES list, so every entry here must match
// exactly (case-insensitive). Aliases kept for backwards-compatibility with any
// older values already in the database.

const NAME_TO_ISO: Record<string, string> = {
	// A
	afghanistan: "af",
	albania: "al",
	algeria: "dz",
	andorra: "ad",
	angola: "ao",
	"antigua and barbuda": "ag",
	argentina: "ar",
	armenia: "am",
	australia: "au",
	austria: "at",
	azerbaijan: "az",
	// B
	bahamas: "bs",
	bahrain: "bh",
	bangladesh: "bd",
	barbados: "bb",
	belarus: "by",
	belgium: "be",
	belize: "bz",
	benin: "bj",
	bhutan: "bt",
	bolivia: "bo",
	"bosnia and herzegovina": "ba",
	botswana: "bw",
	brazil: "br",
	brunei: "bn",
	bulgaria: "bg",
	"burkina faso": "bf",
	burundi: "bi",
	// C
	"cabo verde": "cv",
	cambodia: "kh",
	cameroon: "cm",
	canada: "ca",
	"central african republic": "cf",
	chad: "td",
	chile: "cl",
	china: "cn",
	colombia: "co",
	comoros: "km",
	"congo (brazzaville)": "cg",
	"congo (kinshasa)": "cd",
	"costa rica": "cr",
	croatia: "hr",
	cuba: "cu",
	cyprus: "cy",
	"czech republic": "cz",
	// D
	denmark: "dk",
	djibouti: "dj",
	dominica: "dm",
	"dominican republic": "do",
	// E
	ecuador: "ec",
	egypt: "eg",
	"el salvador": "sv",
	"equatorial guinea": "gq",
	eritrea: "er",
	estonia: "ee",
	eswatini: "sz",
	ethiopia: "et",
	// F
	fiji: "fj",
	finland: "fi",
	france: "fr",
	// G
	gabon: "ga",
	gambia: "gm",
	georgia: "ge",
	germany: "de",
	ghana: "gh",
	greece: "gr",
	grenada: "gd",
	guatemala: "gt",
	guinea: "gn",
	"guinea-bissau": "gw",
	guyana: "gy",
	// H
	haiti: "ht",
	honduras: "hn",
	hungary: "hu",
	// I
	iceland: "is",
	india: "in",
	indonesia: "id",
	iran: "ir",
	iraq: "iq",
	ireland: "ie",
	israel: "il",
	italy: "it",
	"ivory coast": "ci",
	// J
	jamaica: "jm",
	japan: "jp",
	jordan: "jo",
	// K
	kazakhstan: "kz",
	kenya: "ke",
	kiribati: "ki",
	kuwait: "kw",
	kyrgyzstan: "kg",
	// L
	laos: "la",
	latvia: "lv",
	lebanon: "lb",
	lesotho: "ls",
	liberia: "lr",
	libya: "ly",
	liechtenstein: "li",
	lithuania: "lt",
	luxembourg: "lu",
	// M
	madagascar: "mg",
	malawi: "mw",
	malaysia: "my",
	maldives: "mv",
	mali: "ml",
	malta: "mt",
	"marshall islands": "mh",
	mauritania: "mr",
	mauritius: "mu",
	mexico: "mx",
	micronesia: "fm",
	moldova: "md",
	monaco: "mc",
	mongolia: "mn",
	montenegro: "me",
	morocco: "ma",
	mozambique: "mz",
	myanmar: "mm",
	// N
	namibia: "na",
	nauru: "nr",
	nepal: "np",
	netherlands: "nl",
	"new zealand": "nz",
	nicaragua: "ni",
	niger: "ne",
	nigeria: "ng",
	"north korea": "kp",
	"north macedonia": "mk",
	norway: "no",
	// O
	oman: "om",
	// P
	pakistan: "pk",
	palau: "pw",
	palestine: "ps",
	panama: "pa",
	"papua new guinea": "pg",
	paraguay: "py",
	peru: "pe",
	philippines: "ph",
	poland: "pl",
	portugal: "pt",
	// Q
	qatar: "qa",
	// R
	romania: "ro",
	russia: "ru",
	rwanda: "rw",
	// S
	"saint kitts and nevis": "kn",
	"saint lucia": "lc",
	"saint vincent and the grenadines": "vc",
	samoa: "ws",
	"san marino": "sm",
	"são tomé and príncipe": "st",
	"saudi arabia": "sa",
	senegal: "sn",
	serbia: "rs",
	seychelles: "sc",
	"sierra leone": "sl",
	singapore: "sg",
	slovakia: "sk",
	slovenia: "si",
	"solomon islands": "sb",
	somalia: "so",
	"south africa": "za",
	"south korea": "kr",
	"south sudan": "ss",
	spain: "es",
	"sri lanka": "lk",
	sudan: "sd",
	suriname: "sr",
	sweden: "se",
	switzerland: "ch",
	syria: "sy",
	// T
	taiwan: "tw",
	tajikistan: "tj",
	tanzania: "tz",
	thailand: "th",
	"timor-leste": "tl",
	togo: "tg",
	tonga: "to",
	"trinidad and tobago": "tt",
	tunisia: "tn",
	turkey: "tr",
	turkmenistan: "tm",
	tuvalu: "tv",
	// U
	uganda: "ug",
	ukraine: "ua",
	"united arab emirates": "ae",
	"united kingdom": "gb",
	"united states": "us",
	uruguay: "uy",
	uzbekistan: "uz",
	// V
	vanuatu: "vu",
	"vatican city": "va",
	venezuela: "ve",
	vietnam: "vn",
	// Y
	yemen: "ye",
	// Z
	zambia: "zm",
	zimbabwe: "zw",
	// Aliases for backwards-compatibility
	"cote d'ivoire": "ci",
	czechia: "cz",
	"hong kong": "hk",
	trinidad: "tt",
	uk: "gb",
	england: "gb",
	britain: "gb",
	"great britain": "gb",
	scotland: "gb",
	wales: "gb",
	uae: "ae",
	usa: "us",
	"united states of america": "us",
	america: "us",
};

function iso2ToFlag(cc: string): string {
	return cc
		.toUpperCase()
		.replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

// Returns the flag emoji for a country name, or "" when unknown/empty.
export function countryFlag(name: string | null | undefined): string {
	if (!name) return "";
	const iso = NAME_TO_ISO[name.trim().toLowerCase()];
	return iso ? iso2ToFlag(iso) : "";
}
