// Shared option lists for the "who you are" personalization fields
// (profiles.career_stage / fields / country). Used by both the onboarding flow
// and the editable Preferences section on Profile so the two never drift, the
// stored value must round-trip identically between where it's set and where
// it's edited.

// Single-select. Stored verbatim in profiles.career_stage so the personalize
// prompt reads naturally ("Career stage: 0 to 2 years in").
export const CAREER_STAGES: { value: string; sub: string }[] = [
	{ value: "Student", sub: "Still studying" },
	{ value: "About to graduate", sub: "In the final stretch" },
	{ value: "0 to 2 years in", sub: "Just getting started" },
	{ value: "3 to 5 years in", sub: "Finding my stride" },
	{ value: "6+ years in", sub: "Well established" },
	{ value: "Building my own thing", sub: "Self-employed or founder" },
];

// Multi-select up to 2, the biggest relevance lever for a global audience, so
// we keep it focused. Stored in profiles.fields (text[]).
export const FIELDS = [
	"Tech / Engineering",
	"Design",
	"Business / Finance",
	"Marketing / Growth",
	"Science / Research",
	"Creative / Media",
	"Social impact",
	"Still figuring it out",
];
export const MAX_FIELDS = 2;

// Topical / creative interests beyond work or study. Stored in profiles.interests
// (text[]); the user can add their own via a free-text "other" field. Drives
// non-academic opportunity matching and feed personalization.
export const INTEREST_OPTIONS = [
	"Poetry",
	"Writing",
	"Music",
	"Visual art",
	"Photography",
	"Film",
	"Fashion",
	"Dance",
	"Theatre",
	"Sport",
	"Gaming",
	"Activism",
	"Faith",
	"Cooking",
	"Travel",
	"Nature",
];

// All UN member states + a few territories, alphabetical order.
// Each name must match a key in flag.ts NAME_TO_ISO (case-insensitive) to
// render a flag emoji on community surfaces.
export const COUNTRIES = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo (Brazzaville)",
	"Congo (Kinshasa)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Ivory Coast",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Korea",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"São Tomé and Príncipe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Korea",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe",
];
